var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                 xxxxx      oo  ",
   "                                                                 x!!!x          ",
   "                       o             o o                         x!!!x       o  ",
   "                                                                 xx!xx          ",
   "                         o         xxxxx                          xvx        o  ",
   "                                                                  x x     xx    ",
   "                             o                 o                                ",
   "                xxx         xxxx                                        x       ",
   "                                               xxxxx                            ",
   "                                                             oo         o x     ",
   "    @  o o o o i      i                   o o                         xxxxx  i o",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx      xxxxxxxx",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxx      xxxxxxxx",
   "    xxxxxxxxx           xxxxxx!!!!!xxxxx       xxxxxx!!!!!!!xxxxxx   xxxxxxxxxxx",
   "     xxxxxxxxxx        xxxx!!!!!!!!xxxxxxx       xxxx!!!!!!!xxxxxx   xxxxxxxxxxx",
   "      xxxxxxxxxx    !!!!!!!!xxxxxxxxxxxxxxxx!!!!!!!!!!xxxxxxxxxxxx   xxxxxxxxxxx",
   "    xxxxxxxxxxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxx"],


  ["                                      x!!x                        xxxxxxxxx                                  x!xxx",
   "                                      x!!x                     xxxx       xxxxx                              x!xxx",
   "                                      x!!xxxxxxxxxx           xx              xx                             x!xxx",
   "                                      xx!!!!!!!!!!xx         xx                               i              x!xxx",
   "                                      xxxxxxxxxxx!!x         x                                    o   o   o xx!xxx",
   "                                                xx!x         x     o   o           x    o     i             xx!xxx",
   "                                                 x!x         x                         xxxxxxxxxxxxxxxxxxxxxx!!xxx",
   "                                                 xvx         x     xx   xx             x!!!!!!!!!!!!!!!!!!!!!!xxxx",
   "                                                              xx  |   |   |  xx        x!xxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                     o         xx!!!!!!!!!!!xx         xvx                        ",
   "                  i                                  o          xxxx!!!!!xxxx                    i                ",
   "                                               x     x             xxxxxxx        xxx     o      xxxxxxxxxxxxxxxxx",
   "                                               x     x                             xx               xxxxxxxxxxxxxx",
   "                                               x     x                       o     xx                   xxxxxxxxxx",
   "                  i            o               xo    x                       x     xx                        xxxxx",
   "                                               xx    x                             xxx                         xxx",
   "                  i                            x     x      o  o     x  x         xxx     xx     o             xxx",
   "               xxxxxxx        xxx   xxx        x     x               x!!x        ixxx            x              xx",
   "              xxxxxxxxx         x   x          x    ox     xxxxx    xx!!x   xxxxxxxxx                           xx",
   "             xxxxxxxxxxx        x o x  x       x    xx               x!!x    xxx                                xx",
   "     @       xxxxxxxxxxx  o          x         x     x            o  x!!x o                         o           xx",
   "    xxx      xxxxxxxxxxx  x          x    x            o  x   xxxxx  xxxxxx      x                  xx          xx",
   "    xxx      xxxxxxxxxxx      xx  o  xx        x      xx             xx      o   x x        xxx             o o xx",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!!xx     xx!!!!!!!!xx    xx!!!!!!!!!!    xx    =     x x        xx             xxxxxxx",
   "!!!!xx!!!!!!!xxxxxxxxxxx!!!!!xx       xxxxxxxxxx     xx!!!!!!!xx!!   xxxxxxxxxxxxxxxx  o o  xx!!!!!!!!!!!!!xxxxxxx",
   "!!!!xxx!!!!!!!!!xxxxxxxx!!!!!x  io                 xx!!!!!!xxxxx!!   xxxxxxxxxxxxxxxx  =    xx!!!!!!!!!!!!!!xxxxxx",
   "!!!!xxx!!!!!!!!xxxxxxxxx!!!!!x                     xx!!!!!!xxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!xxxx",
   "!!!!!xx!!!!!!!xxxxxxxxxx!!!!!xxi      xxxxxxxxxxxxxx!!!!!!xxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!xxx!!!!!!!!xxxxxxxxx!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!xxxxx"],

  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        i                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       xxx                 iii        iii  xxx                                ",
   "                                     o xxx                 ixi        ixi      i                              ",
   "                                     xxxxxxx                x          x                                      ",
   "                                      xxxxx                 x   oooo   x       xxx                            ",
   "                                    o xxxxx                 xxxxxxxxxxxx       xxx       x                    ",
   "                                     xxxxxxxxxxxxx i     xxxxxx                                               ",
   "                                      xxxxxxxxxxxxxx   xxxxxxxx                       x                       ",
   "                                      xxxxxx           xx                                                     ",
   "                                     oxxxxx           xx                     xxxxx i        x                 ",
   "                                     xxxxxx           xx                                                      ",
   "                                      xxxxx= = = =    xx            xxx                                       ",
   "                                      xxxxx           xx           x!!!x                x                     ",
   "                                      xxxxx    = = = =xx     o      xxx      xxxxx                            ",
   "                                     xxxxxxx          xx                     x!!!x                            ",
   "                              o   o   xxxxx           xx     x                xvx        xxx                  ",
   "                                      xxxxx           xx        xxxxxxxx                x!!!x                 ",
   "                             xxx xxx xxxxxxx     o o  x!!!!!!!!!!!!!!xx                  xvx                  ",
   "                             xxx xxxixxxxxxx          x!!!!!!!!!!!!!!xx                                       ",
   "                                          xi  xxxxxxxxxxxxxxxxxxxxxxx                                         ",
   "  @                           xx           x  xxxxxxxxxxxxxxxxxxxxxxx                xx                       ",
   "  x                            xxx                                          x                    xxx          ",
   "  xx                                                                               xxxx                       ",
   "  xxx                               xxx    xxxxxxx                        xxxxx                               ",
   "  xxxx              o                                                                                         ",
   "  xxxxx                           xx                                                                          ",
   "  xxxxxx                    o o          x       |xxxxx|    |xxxx|     |xxx xxx|                              ",
   "  xxxxxxx                xxxxxxxxo             o o                                  x         xxx          x  ",
   "  xxxxxxxx               xxxxxxxxx                                       xxx       x!!!x         x         x  ",
   "  xxxxxxxxx                       xxxo o oxx                             x x        xxx         xxx        x  ",
   "  xxxxxxxxxx        x             xxxxxxxxxxxxx  x  o  x    x    x     x     xxxx               xxx        x  ",
   "  xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx!!x    x!!!xxx!!!x!!!!x!!!!xx   xx         x        x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxx!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],                                                                                                         
   

  ["                                                                                                  xxxxxxxxxxxx",
   "                                      o                                                               x       ",
   " xxxx                                                                                              o    xxxxx ",
   " x!!x                       o                                                                      x          ",
   " xxxx                                                                                                 x xxx   ",
   "                   o o     xxx    x   x                                                             x x x     ",
   "      =      o             =                 =               =                            =  xxx x            ",
   "                   xxx                                       o                        o               x       ",
   "       x!!!xxx           o                i ix              xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx         ",
   "       x!!!!xxxx                                              x   x x   x x   x x   x x   x x   x x           ",
   "       xxxxxx            x                                   xx x xxx x xxx x xxx x xxx x xxx x xxxxx         ",
   "                                                            o   xix   xix   xix   xix   xix   xix     x       ",
   "   =                  =                    =               xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx         ",
   "                                                         o                                                    ",
   "                        xxx                              xx                                                   ",
   "                                                                                                              ",
   "    =          =             =                      =     o                =          o                       ",
   "                                                      xx                       o                              ",
   "                   xxx         xxx                               o                                            ",
   "                                                        i                                   o                 ",
   "                                                                               x      x                       ",
   "              =          =           =               =    xx     xx        i       i                          ",
   "             xxx!!!!!!!!xxx!!!!!!!!!!xxx                                 x                  x                 ",
   "             xxxxxxxxxxxxxxxxxxxxxxxxxxx                                         o                            ",
   "                                                                            o                                 ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                             xxxxx                  ",
   "  x         x   x       x   x       x   x                                   x     x                           ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "  xxxxxxx                                  x   x                     xxx                                      ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]

  ];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
